services:
  backend:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: "seo-admin-backend_script_${TIMESTAMP}"
    network_mode: "host"
    ports:
      - '8000:8000'
    volumes:
      - ./data:/data
    restart: unless-stopped
  